//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmsgptcloud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smsEntities : DbContext
    {
        public smsEntities()
            : base("name=smsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<compute_node> compute_node { get; set; }
        public virtual DbSet<configuration_properties> configuration_properties { get; set; }
        public virtual DbSet<database_file> database_file { get; set; }
        public virtual DbSet<distributions> distributions { get; set; }
        public virtual DbSet<filegroups> filegroups { get; set; }
        public virtual DbSet<nodes> nodes { get; set; }
        public virtual DbSet<pdw_sp_configure> pdw_sp_configure { get; set; }
        public virtual DbSet<quition1> quition1 { get; set; }
        public virtual DbSet<quitions> quitions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_order> tb_order { get; set; }
        public virtual DbSet<tb_quition> tb_quition { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<version_history> version_history { get; set; }
    }
}
