//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmsgptcloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quitions
    {
        public int QId { get; set; }
        public string mname { get; set; }
        public string Qquition { get; set; }
        public string Qanuser { get; set; }
        public string Qcode { get; set; }
        public string Qnote { get; set; }
        public string Filename { get; set; }
    }
}
