//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmsgptcloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        public int orid { get; set; }
        public string username { get; set; }
        public string ormesg { get; set; }
        public string orfile { get; set; }
        public string orpictire { get; set; }
        public Nullable<System.TimeSpan> ortime { get; set; }
    }
}
