//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmsgptcloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_quition
    {
        public decimal qid { get; set; }
        public string qname { get; set; }
        public string qanser { get; set; }
        public string qcode { get; set; }
        public string qtrans { get; set; }
    }
}
