//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmsgptcloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public string useremail { get; set; }
        public string useraddress { get; set; }
        public string userphone { get; set; }
        public string usersub { get; set; }
        public Nullable<bool> state { get; set; }
    }
}
